import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms of Service for SplitVote.io.',
  robots: { index: true, follow: true },
  alternates: {
    canonical: 'https://splitvote.io/terms',
    languages: {
      'en': 'https://splitvote.io/terms',
      'it-IT': 'https://splitvote.io/it/terms',
      'x-default': 'https://splitvote.io/terms',
    },
  },
}

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-16 text-[var(--text)]">
      <h1 className="text-3xl font-black mb-2">Terms of Service</h1>
      <p className="text-sm text-[var(--muted)] mb-10">Last updated: April 28, 2026</p>

      <section className="space-y-6 text-sm leading-relaxed text-[var(--muted)]">

        <div>
          <h2 className="text-base font-bold text-white mb-2">1. Acceptance of terms</h2>
          <p>
            By accessing or using SplitVote.io (&ldquo;the Service&rdquo;), you agree to be bound by
            these Terms of Service. If you do not agree, please do not use the Service.
          </p>
        </div>

        <div>
          <h2 className="text-base font-bold text-white mb-2">2. Description of the service</h2>
          <p>
            SplitVote.io is an anonymous online voting platform that presents moral dilemmas and
            displays real-time aggregated results. The Service is provided for entertainment and
            educational purposes only. No vote, result, or content on the Service constitutes
            medical, legal, financial, or any other professional advice. Vote results are not
            scientifically representative samples of any population.
          </p>
        </div>

        <div>
          <h2 className="text-base font-bold text-white mb-2">3. Eligibility</h2>
          <p>
            You must be at least 13 years of age to use the Service. By using the Service, you
            represent and warrant that you meet this age requirement. If you are under 18, you should
            review these Terms with a parent or guardian.
          </p>
        </div>

        <div>
          <h2 className="text-base font-bold text-white mb-2">4. Accounts and gamification</h2>
          <p>
            You may use the Service anonymously without creating an account. If you register, you
            receive a pseudonymous display name (&ldquo;Splitvoter-XXXXXX&rdquo;) and access to
            gamification features: XP points, streaks, badges, and daily missions. You are
            responsible for maintaining the confidentiality of your account. We reserve the right
            to remove or rename accounts that violate these Terms.
          </p>
        </div>

        <div>
          <h2 className="text-base font-bold text-white mb-2">5. Acceptable use</h2>
          <p className="mb-2">You agree not to:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Attempt to manipulate vote counts through automated means, bots, or scripts</li>
            <li>Reverse engineer, scrape, or crawl the Service in a way that imposes unreasonable load</li>
            <li>Use the Service for any unlawful purpose or in violation of applicable laws</li>
            <li>Attempt to circumvent any security measures or rate limits</li>
            <li>Submit content that is offensive, defamatory, sexually explicit, or identifies real individuals in harmful ways</li>
          </ul>
        </div>

        <div>
          <h2 className="text-base font-bold text-white mb-2">6. User-submitted content</h2>
          <p>
            Premium subscribers may submit dilemma suggestions. Submitted content remains your
            property, but by submitting you grant SplitVote.io a worldwide, non-exclusive,
            royalty-free licence to display and distribute the content on the Service. All
            user-submitted dilemmas are subject to editorial review before publication. We reserve
            the right to reject, modify, or remove any content without notice.
          </p>
        </div>

        <div>
          <h2 className="text-base font-bold text-white mb-2">7. AI-generated content</h2>
          <p>
            Some dilemmas on the Service are generated by AI systems (Anthropic Claude or models
            via OpenRouter). All AI-generated content is reviewed and approved by a human
            administrator before becoming publicly visible. We do not warrant that AI-generated
            content is accurate, complete, or free from bias.
          </p>
        </div>

        <div>
          <h2 className="text-base font-bold text-white mb-2">8. Premium subscription and payments</h2>
          <p className="mb-2">
            SplitVote.io offers optional paid features:
          </p>
          <ul className="list-disc pl-5 space-y-1">
            <li><strong className="text-white">Premium subscription</strong> — removes ads and unlocks unlimited display name changes. Billed via Stripe on a recurring basis.</li>
            <li><strong className="text-white">One-time name change</strong> — free users receive one free rename; additional renames require a one-time payment processed by Stripe.</li>
          </ul>
          <p className="mt-2">
            All payments are processed by Stripe. We do not store payment card details. You can
            manage or cancel your Premium subscription at any time through the customer portal
            accessible from your profile dashboard. Cancellation takes effect at the end of the
            current billing period. Refunds are evaluated on a case-by-case basis; contact{' '}
            <a href="mailto:support@splitvote.io" className="text-blue-400 hover:underline">
              support@splitvote.io
            </a>{' '}
            within 14 days of purchase.
          </p>
          <p className="mt-2">
            Nothing in these Terms limits any statutory consumer rights you may have under
            applicable EU or Italian law.
          </p>
        </div>

        <div>
          <h2 className="text-base font-bold text-white mb-2">9. Intellectual property</h2>
          <p>
            All original content on the Service, including text, graphics, logos, and code,
            is owned by SplitVote.io or its licensors and is protected by applicable intellectual
            property laws. You may share results and screenshots for personal, non-commercial use with
            attribution to SplitVote.io.
          </p>
        </div>

        <div>
          <h2 className="text-base font-bold text-white mb-2">10. Third-party advertising</h2>
          <p>
            The Service may display advertisements served by Google AdSense. We are not responsible
            for the content of third-party advertisements. Clicking on advertisements is at your own
            risk. Premium subscribers do not see advertisements.
          </p>
        </div>

        <div>
          <h2 className="text-base font-bold text-white mb-2">11. Moderation and termination</h2>
          <p>
            We reserve the right to suspend or terminate accounts, remove content, or restrict access
            to the Service at our sole discretion, without prior notice, if we determine that a user
            has violated these Terms or is otherwise acting in a manner harmful to the Service or
            other users.
          </p>
        </div>

        <div>
          <h2 className="text-base font-bold text-white mb-2">12. Disclaimers</h2>
          <p>
            The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind,
            express or implied. We do not warrant that the Service will be uninterrupted or
            error-free. Vote results are not scientifically representative samples of any population
            and should not be relied upon for any decision-making.
          </p>
        </div>

        <div>
          <h2 className="text-base font-bold text-white mb-2">13. Limitation of liability</h2>
          <p>
            To the fullest extent permitted by law, SplitVote.io shall not be liable for any indirect,
            incidental, special, consequential, or punitive damages arising from your use of the
            Service. Our total aggregate liability shall not exceed €100 or the amount you paid us in
            the 12 months preceding the claim, whichever is greater.
          </p>
        </div>

        <div>
          <h2 className="text-base font-bold text-white mb-2">14. Privacy</h2>
          <p>
            Your use of the Service is also governed by our{' '}
            <a href="/privacy" className="text-blue-400 hover:underline">Privacy Policy</a>,
            which is incorporated into these Terms by reference.
          </p>
        </div>

        <div>
          <h2 className="text-base font-bold text-white mb-2">15. Governing law</h2>
          <p>
            These Terms shall be governed by and construed in accordance with the laws of Italy.
            Any disputes shall be subject to the exclusive jurisdiction of the courts of Italy.
            Nothing in this clause affects any mandatory consumer protection rights you may have
            under applicable EU law.
          </p>
        </div>

        <div>
          <h2 className="text-base font-bold text-white mb-2">16. Changes to terms</h2>
          <p>
            We reserve the right to modify these Terms at any time. We will notify users of material
            changes by updating the &ldquo;Last updated&rdquo; date. Continued use of the Service
            after changes constitutes acceptance of the revised Terms.
          </p>
        </div>

        <div>
          <h2 className="text-base font-bold text-white mb-2">17. Contact</h2>
          <p>
            For any questions regarding these Terms, please contact:{' '}
            <a href="mailto:legal@splitvote.io" className="text-blue-400 hover:underline">
              legal@splitvote.io
            </a>
          </p>
        </div>

      </section>
    </div>
  )
}
