import type { Category } from './scenarios'

export type ContentSeedStyle = 'moral' | 'lifestyle'

export interface ContentSeed {
  id: string
  topic: string
  category: Category
  style: ContentSeedStyle
  packId: string
  angle?: string
  notes?: string
}

export interface ContentSeedPack {
  id: string
  label: string
  targetShare: number
  description: string
  seeds: Omit<ContentSeed, 'packId'>[]
}

export const CONTENT_SEED_USAGE_REDIS_KEY = 'content:seed-usage:v1'

export const CONTENT_SEED_PACKS: ContentSeedPack[] = [
  {
    id: 'work-career',
    label: 'Work / Career',
    targetShare: 0.12,
    description: 'Everyday workplace dilemmas with concrete trade-offs around fairness, ambition, loyalty, and automation.',
    seeds: [
      { id: 'salary-transparency-coworkers', topic: 'salary transparency between coworkers', category: 'justice', style: 'moral' },
      { id: 'remote-work-office-fairness', topic: 'remote work privilege vs office fairness', category: 'justice', style: 'moral' },
      { id: 'firing-underperforming-friend', topic: 'firing an underperforming friend', category: 'loyalty', style: 'moral' },
      { id: 'ai-replacing-junior-employees', topic: 'AI replacing junior employees', category: 'technology', style: 'moral' },
      { id: 'burnout-leave-overloaded-team', topic: 'burnout leave when the team is overloaded', category: 'relationships', style: 'moral' },
      { id: 'refusing-unpaid-overtime', topic: 'refusing unpaid overtime', category: 'freedom', style: 'moral' },
      { id: 'reporting-toxic-manager', topic: 'reporting a toxic manager', category: 'justice', style: 'moral' },
      { id: 'taking-credit-for-team-work', topic: 'taking credit for team work', category: 'loyalty', style: 'moral' },
      { id: 'higher-pay-while-others-struggle', topic: 'negotiating higher pay while others struggle', category: 'justice', style: 'moral' },
      { id: 'culture-fit-vs-skill', topic: 'hiring for culture fit vs skill', category: 'society', style: 'moral' },
      { id: 'workplace-productivity-surveillance', topic: 'workplace surveillance for productivity', category: 'technology', style: 'moral' },
      { id: 'return-office-company-culture', topic: 'returning to office to save company culture', category: 'society', style: 'moral' },
      { id: 'quitting-without-notice', topic: 'quitting without notice after mistreatment', category: 'freedom', style: 'moral' },
      { id: 'exposing-pay-discrimination', topic: 'exposing pay discrimination', category: 'justice', style: 'moral' },
      { id: 'automating-colleague-job', topic: "automating a colleague's job", category: 'technology', style: 'moral' },
    ],
  },
  {
    id: 'couples-dating',
    label: 'Couples / Dating',
    targetShare: 0.10,
    description: 'Relationship dilemmas around trust, money, privacy, commitment, and social pressure.',
    seeds: [
      { id: 'financial-secrecy-relationship', topic: 'financial secrecy in a relationship', category: 'relationships', style: 'moral' },
      { id: 'reading-partner-messages', topic: "reading a partner's messages", category: 'relationships', style: 'moral' },
      { id: 'forgiving-cheating-once', topic: 'forgiving cheating once', category: 'relationships', style: 'moral' },
      { id: 'staying-together-for-children', topic: 'staying together for children', category: 'relationships', style: 'moral' },
      { id: 'open-relationship-ultimatum', topic: 'open relationship ultimatum', category: 'relationships', style: 'moral' },
      { id: 'moving-abroad-for-partner-career', topic: "moving abroad for a partner's career", category: 'relationships', style: 'moral' },
      { id: 'hiding-past-relationships', topic: 'hiding past relationships', category: 'relationships', style: 'moral' },
      { id: 'splitting-rent-by-income', topic: 'splitting rent by income', category: 'justice', style: 'moral' },
      { id: 'family-disapproval-partner', topic: 'family disapproval of a partner', category: 'loyalty', style: 'moral' },
      { id: 'sharing-location-permanently', topic: 'sharing location permanently with a partner', category: 'freedom', style: 'moral' },
      { id: 'prenuptial-agreement-fairness', topic: 'prenuptial agreement fairness', category: 'justice', style: 'moral' },
      { id: 'emotional-vs-physical-cheating', topic: 'emotional cheating vs physical cheating', category: 'relationships', style: 'moral' },
      { id: 'breaking-up-by-text', topic: 'breaking up by text', category: 'relationships', style: 'moral' },
      { id: 'dating-friend-ex', topic: "dating a friend's ex", category: 'loyalty', style: 'moral' },
      { id: 'backup-plan-relationship', topic: 'keeping a backup plan relationship', category: 'relationships', style: 'moral' },
    ],
  },
  {
    id: 'family-parents',
    label: 'Family / Parents',
    targetShare: 0.10,
    description: 'Family choices where care, control, fairness, and obligation conflict.',
    seeds: [
      { id: 'tracking-teen-phone', topic: "tracking a teenager's phone", category: 'freedom', style: 'moral' },
      { id: 'posting-children-photos-online', topic: "posting children's photos online", category: 'technology', style: 'moral' },
      { id: 'inheritance-help-one-child', topic: 'choosing one child for inheritance help', category: 'justice', style: 'moral' },
      { id: 'elderly-parent-care-vs-career', topic: 'elderly parent care vs career', category: 'loyalty', style: 'moral' },
      { id: 'forcing-child-apologize', topic: 'forcing a child to apologize', category: 'relationships', style: 'moral' },
      { id: 'private-school-one-child', topic: 'paying for private school for one child', category: 'justice', style: 'moral' },
      { id: 'hiding-family-debt', topic: 'hiding family debt', category: 'loyalty', style: 'moral' },
      { id: 'cutting-off-toxic-relative', topic: 'cutting off a toxic relative', category: 'relationships', style: 'moral' },
      { id: 'disciplining-another-child', topic: "disciplining another person's child", category: 'society', style: 'moral' },
      { id: 'painful-family-truth', topic: 'telling children a painful family truth', category: 'loyalty', style: 'moral' },
      { id: 'embryo-selection-family', topic: 'IVF embryo selection ethics', category: 'technology', style: 'moral' },
      { id: 'caring-for-absent-parents', topic: 'caring for parents who were absent', category: 'loyalty', style: 'moral' },
      { id: 'moving-away-family-obligations', topic: 'moving away from family obligations', category: 'freedom', style: 'moral' },
      { id: 'grandparents-override-rules', topic: 'letting grandparents override rules', category: 'relationships', style: 'moral' },
      { id: 'siblings-inheritance-conflict', topic: 'siblings fighting over inheritance', category: 'justice', style: 'moral' },
    ],
  },
  {
    id: 'friends-loyalty',
    label: 'Friends / Loyalty',
    targetShare: 0.08,
    description: 'Friendship conflicts that force loyalty, honesty, safety, and boundaries into collision.',
    seeds: [
      { id: 'friend-drunk-driving', topic: "reporting a friend's drunk driving", category: 'loyalty', style: 'moral' },
      { id: 'friend-cheating-secret', topic: "keeping a friend's cheating secret", category: 'loyalty', style: 'moral' },
      { id: 'lending-money-friend', topic: 'lending money you may never get back', category: 'relationships', style: 'moral' },
      { id: 'excluding-friend-trip', topic: 'excluding one friend from a trip', category: 'relationships', style: 'moral' },
      { id: 'racist-jokes-friend-group', topic: 'confronting racist jokes in a friend group', category: 'justice', style: 'moral' },
      { id: 'friend-bad-partner', topic: 'telling a friend their partner is bad for them', category: 'loyalty', style: 'moral' },
      { id: 'choosing-between-friends', topic: 'choosing between two friends in conflict', category: 'loyalty', style: 'moral' },
      { id: 'sharing-private-screenshots', topic: 'sharing private screenshots', category: 'technology', style: 'moral' },
      { id: 'ghosting-draining-friend', topic: 'ghosting a draining friend', category: 'relationships', style: 'moral' },
      { id: 'friend-resume-lie', topic: 'helping a friend lie on a resume', category: 'loyalty', style: 'moral' },
      { id: 'standing-by-cancelled-friend', topic: 'standing by a cancelled friend', category: 'loyalty', style: 'moral' },
      { id: 'friend-addiction-family', topic: "revealing a friend's addiction to family", category: 'loyalty', style: 'moral' },
      { id: 'refusing-wedding-role', topic: 'refusing to be best man or maid of honor', category: 'relationships', style: 'moral' },
      { id: 'friendship-over-politics', topic: 'ending friendship over politics', category: 'society', style: 'moral' },
      { id: 'defending-wrong-friend', topic: 'defending a friend who is wrong', category: 'loyalty', style: 'moral' },
    ],
  },
  {
    id: 'money-class-fairness',
    label: 'Money / Class / Fairness',
    targetShare: 0.08,
    description: 'Economic trade-offs about obligation, fairness, privilege, and redistribution.',
    seeds: [
      { id: 'wealth-tax-billionaires', topic: 'wealth tax on billionaires', category: 'justice', style: 'moral' },
      { id: 'student-debt-forgiveness', topic: 'forgiving student debt', category: 'justice', style: 'moral' },
      { id: 'tipping-fatigue', topic: 'tipping fatigue', category: 'society', style: 'moral' },
      { id: 'luxury-spending-during-crisis', topic: 'buying luxury goods during crisis', category: 'society', style: 'moral' },
      { id: 'inheritance-tax-fairness', topic: 'inheritance tax fairness', category: 'justice', style: 'moral' },
      { id: 'rent-control-landlord-rights', topic: 'rent control vs landlord rights', category: 'justice', style: 'moral' },
      { id: 'universal-basic-income', topic: 'universal basic income', category: 'society', style: 'moral' },
      { id: 'unpaid-internships', topic: 'unpaid internships', category: 'justice', style: 'moral' },
      { id: 'charity-with-strings', topic: 'charity with strings attached', category: 'justice', style: 'moral' },
      { id: 'returning-found-cash', topic: 'returning found cash', category: 'morality', style: 'moral' },
      { id: 'price-gouging-shortages', topic: 'price gouging during shortages', category: 'justice', style: 'moral' },
      { id: 'family-connections-job', topic: 'using family connections for a job', category: 'justice', style: 'moral' },
      { id: 'influencer-exposure-payment', topic: 'paying influencers with exposure', category: 'society', style: 'moral' },
      { id: 'split-bills-income', topic: 'splitting bills equally vs by income', category: 'justice', style: 'moral' },
      { id: 'lottery-family-obligations', topic: 'lottery winner obligations to family', category: 'loyalty', style: 'moral' },
    ],
  },
  {
    id: 'technology-ai',
    label: 'Technology / AI',
    targetShare: 0.10,
    description: 'Technology dilemmas with concrete harms, control questions, authorship, and accountability.',
    seeds: [
      { id: 'deepfake-evidence-guilty', topic: 'deepfake evidence against a guilty person', category: 'technology', style: 'moral' },
      { id: 'ai-judges-minor-cases', topic: 'AI judges in minor cases', category: 'technology', style: 'moral' },
      { id: 'ai-therapist-replacement', topic: 'AI therapist replacing human therapists', category: 'technology', style: 'moral' },
      { id: 'autonomous-car-passenger-pedestrian', topic: 'autonomous car passenger vs pedestrian', category: 'technology', style: 'moral' },
      { id: 'ai-art-living-artists', topic: 'AI art trained on living artists', category: 'technology', style: 'moral' },
      { id: 'workplace-ai-monitoring', topic: 'workplace AI monitoring', category: 'technology', style: 'moral' },
      { id: 'facial-recognition-schools', topic: 'facial recognition in schools', category: 'technology', style: 'moral' },
      { id: 'children-smartphone-ban', topic: 'banning children from smartphones', category: 'technology', style: 'moral' },
      { id: 'neural-implants-productivity', topic: 'neural implants for productivity', category: 'technology', style: 'moral' },
      { id: 'algorithmic-hiring-fairness', topic: 'algorithmic hiring fairness', category: 'technology', style: 'moral' },
      { id: 'robot-caregivers-elderly', topic: 'robot caregivers for elderly people', category: 'technology', style: 'moral' },
      { id: 'ai-news-anchors', topic: 'AI-generated news anchors', category: 'technology', style: 'moral' },
      { id: 'cloning-dead-loved-one-voice', topic: "cloning a dead loved one's voice", category: 'technology', style: 'moral' },
      { id: 'predictive-policing', topic: 'predictive policing', category: 'technology', style: 'moral' },
      { id: 'mandatory-digital-id', topic: 'mandatory digital ID', category: 'technology', style: 'moral' },
    ],
  },
  {
    id: 'social-media-internet',
    label: 'Social Media / Internet Culture',
    targetShare: 0.08,
    description: 'Internet culture dilemmas about visibility, accountability, privacy, and monetization.',
    seeds: [
      { id: 'public-shaming-old-posts', topic: 'public shaming for old posts', category: 'society', style: 'moral' },
      { id: 'creator-private-behavior', topic: 'canceling a creator for private behavior', category: 'society', style: 'moral' },
      { id: 'delete-social-media-mental-health', topic: 'deleting all social media for mental health', category: 'technology', style: 'moral' },
      { id: 'exposing-anonymous-trolls', topic: 'exposing anonymous trolls', category: 'technology', style: 'moral' },
      { id: 'filming-strangers-public', topic: 'filming strangers in public', category: 'society', style: 'moral' },
      { id: 'influencer-bad-advice', topic: 'influencer responsibility for bad advice', category: 'society', style: 'moral' },
      { id: 'parents-monetizing-children', topic: "parents monetizing children's lives online", category: 'technology', style: 'moral' },
      { id: 'dating-app-background-checks', topic: 'dating app background checks', category: 'technology', style: 'moral' },
      { id: 'beauty-filter-ad-ban', topic: 'banning filters on beauty ads', category: 'society', style: 'moral' },
      { id: 'paying-for-verification', topic: 'paying for verification', category: 'society', style: 'moral' },
      { id: 'doomscrolling-limits-law', topic: 'doomscrolling limits by law', category: 'freedom', style: 'moral' },
      { id: 'anonymous-confession-pages', topic: 'anonymous confession pages', category: 'technology', style: 'moral' },
      { id: 'viral-charity-videos', topic: 'viral charity videos', category: 'society', style: 'moral' },
      { id: 'posting-during-tragedy', topic: 'posting during tragedy', category: 'society', style: 'moral' },
      { id: 'leaking-private-group-chats', topic: 'leaking private group chats', category: 'technology', style: 'moral' },
    ],
  },
  {
    id: 'society-civic-life',
    label: 'Society / Civic Life',
    targetShare: 0.08,
    description: 'Public-life dilemmas around rights, safety, duty, punishment, protest, and civic obligation.',
    seeds: [
      { id: 'protest-blocking-emergency-traffic', topic: 'protest blocking emergency traffic', category: 'society', style: 'moral' },
      { id: 'mandatory-voting', topic: 'mandatory voting', category: 'freedom', style: 'moral' },
      { id: 'jury-duty-refusal', topic: 'jury duty refusal', category: 'justice', style: 'moral' },
      { id: 'whistleblowing-national-secrets', topic: 'whistleblowing national secrets', category: 'loyalty', style: 'moral' },
      { id: 'climate-flight-restrictions', topic: 'climate restrictions on flights', category: 'society', style: 'moral' },
      { id: 'ban-cars-city-centers', topic: 'banning cars from city centers', category: 'society', style: 'moral' },
      { id: 'street-surveillance-cameras', topic: 'surveillance cameras in every street', category: 'technology', style: 'moral' },
      { id: 'school-vaccine-mandates', topic: 'vaccine mandates for school', category: 'society', style: 'moral' },
      { id: 'controversial-art-public-funding', topic: 'public funding for controversial art', category: 'society', style: 'moral' },
      { id: 'citizens-vs-migrants-priority', topic: 'prioritizing citizens over migrants', category: 'society', style: 'moral' },
      { id: 'prison-punishment-rehabilitation', topic: 'prison punishment vs rehabilitation', category: 'justice', style: 'moral' },
      { id: 'criminal-second-chance', topic: 'giving criminals a second chance', category: 'justice', style: 'moral' },
      { id: 'hate-speech-ban', topic: 'banning hate speech', category: 'freedom', style: 'moral' },
      { id: 'military-draft-crisis', topic: 'military draft in national crisis', category: 'loyalty', style: 'moral' },
      { id: 'civil-disobedience-unjust-laws', topic: 'civil disobedience against unjust laws', category: 'justice', style: 'moral' },
    ],
  },
  {
    id: 'education-school',
    label: 'Education / School',
    targetShare: 0.06,
    description: 'School dilemmas around fairness, pressure, discipline, cheating, phones, and access.',
    seeds: [
      { id: 'ai-homework', topic: 'using AI for homework', category: 'technology', style: 'moral' },
      { id: 'grading-effort-vs-results', topic: 'grading effort vs results', category: 'justice', style: 'moral' },
      { id: 'reporting-friend-cheating', topic: 'reporting cheating by a friend', category: 'loyalty', style: 'moral' },
      { id: 'school-uniforms', topic: 'school uniforms', category: 'freedom', style: 'moral' },
      { id: 'phones-banned-classrooms', topic: 'phones banned in classrooms', category: 'technology', style: 'moral' },
      { id: 'elite-schools-equal-funding', topic: 'elite schools vs equal funding', category: 'justice', style: 'moral' },
      { id: 'teachers-monitor-social-media', topic: 'teachers monitoring student social media', category: 'technology', style: 'moral' },
      { id: 'parents-pressure-teachers-grades', topic: 'parents pressuring teachers for grades', category: 'society', style: 'moral' },
      { id: 'public-student-ranking', topic: 'ranking students publicly', category: 'justice', style: 'moral' },
      { id: 'expelling-bullies', topic: 'expelling bullies', category: 'justice', style: 'moral' },
      { id: 'zero-tolerance-discipline', topic: 'zero-tolerance discipline', category: 'justice', style: 'moral' },
      { id: 'homework-family-hardship', topic: 'homework during family hardship', category: 'relationships', style: 'moral' },
      { id: 'paying-students-good-grades', topic: 'paying students for good grades', category: 'society', style: 'moral' },
      { id: 'hiding-bad-grades', topic: 'hiding bad grades from parents', category: 'loyalty', style: 'moral' },
      { id: 'legacy-college-admissions', topic: 'college admissions legacy preference', category: 'justice', style: 'moral' },
    ],
  },
  {
    id: 'health-bioethics',
    label: 'Health / Body / Bioethics',
    targetShare: 0.07,
    description: 'Health and body dilemmas about scarcity, autonomy, enhancement, and risk.',
    seeds: [
      { id: 'organ-donation-opt-out', topic: 'mandatory organ donation opt-out', category: 'morality', style: 'moral' },
      { id: 'refusing-treatment-religious', topic: 'refusing treatment for religious reasons', category: 'freedom', style: 'moral' },
      { id: 'scarce-icu-bed-allocation', topic: 'scarce ICU bed allocation', category: 'justice', style: 'moral' },
      { id: 'genetic-embryo-selection', topic: 'genetic embryo selection', category: 'technology', style: 'moral' },
      { id: 'assisted-dying', topic: 'assisted dying', category: 'morality', style: 'moral' },
      { id: 'vaccine-refusal-public-spaces', topic: 'vaccine refusal and public spaces', category: 'society', style: 'moral' },
      { id: 'teen-cosmetic-surgery', topic: 'cosmetic surgery for teenagers', category: 'freedom', style: 'moral' },
      { id: 'weight-loss-drugs-appearance', topic: 'using weight-loss drugs for appearance', category: 'society', style: 'moral' },
      { id: 'selling-kidney', topic: 'selling a kidney', category: 'freedom', style: 'moral' },
      { id: 'mental-health-days-work', topic: 'mental health days at work', category: 'relationships', style: 'moral' },
      { id: 'prioritizing-younger-patients', topic: 'prioritizing younger patients', category: 'justice', style: 'moral' },
      { id: 'experimental-drugs-without-approval', topic: 'experimental drugs without approval', category: 'freedom', style: 'moral' },
      { id: 'insurance-penalties-lifestyle', topic: 'health insurance penalties for lifestyle', category: 'justice', style: 'moral' },
      { id: 'dna-databases-crime', topic: 'DNA databases for crime solving', category: 'technology', style: 'moral' },
      { id: 'cloning-extinct-animals', topic: 'cloning extinct animals', category: 'technology', style: 'moral' },
    ],
  },
  {
    id: 'environment-climate',
    label: 'Environment / Climate',
    targetShare: 0.06,
    description: 'Climate dilemmas that trade personal freedom, economic stability, and collective survival.',
    seeds: [
      { id: 'ban-short-flights', topic: 'banning short flights', category: 'society', style: 'moral' },
      { id: 'meat-tax', topic: 'meat tax', category: 'society', style: 'moral' },
      { id: 'climate-protests-property-damage', topic: 'climate protests damaging property', category: 'society', style: 'moral' },
      { id: 'personal-carbon-limits', topic: 'personal carbon limits', category: 'freedom', style: 'moral' },
      { id: 'nuclear-power-expansion', topic: 'nuclear power expansion', category: 'society', style: 'moral' },
      { id: 'geoengineering-atmosphere', topic: 'geoengineering the atmosphere', category: 'technology', style: 'moral' },
      { id: 'corporate-emissions-disclosure', topic: 'forcing companies to disclose emissions', category: 'justice', style: 'moral' },
      { id: 'fast-fashion-ban', topic: 'banning fast fashion', category: 'society', style: 'moral' },
      { id: 'relocating-climate-risk-communities', topic: 'relocating climate-risk communities', category: 'justice', style: 'moral' },
      { id: 'polluting-industry-jobs', topic: 'protecting jobs in polluting industries', category: 'society', style: 'moral' },
      { id: 'water-rationing', topic: 'water rationing', category: 'society', style: 'moral' },
      { id: 'rewilding-farmland', topic: 'rewilding farmland', category: 'society', style: 'moral' },
      { id: 'eco-sabotage', topic: 'eco-sabotage', category: 'society', style: 'moral' },
      { id: 'carbon-credits-rich', topic: 'carbon credits for the rich', category: 'justice', style: 'moral' },
      { id: 'synthetic-meat-schools', topic: 'synthetic meat in schools', category: 'society', style: 'moral' },
    ],
  },
  {
    id: 'lifestyle-identity',
    label: 'Lifestyle / Identity / Daily Choices',
    targetShare: 0.08,
    description: 'Relatable low-friction choices that can go viral without becoming empty preference polls.',
    seeds: [
      { id: 'city-vs-countryside', topic: 'city life vs countryside life', category: 'lifestyle', style: 'lifestyle' },
      { id: 'career-vs-free-time', topic: 'career ambition vs free time', category: 'lifestyle', style: 'lifestyle' },
      { id: 'rent-free-travel-life', topic: 'never owning a home but traveling freely', category: 'lifestyle', style: 'lifestyle' },
      { id: 'minimalist-life-vs-comfort', topic: 'minimalist life vs comfort', category: 'lifestyle', style: 'lifestyle' },
      { id: 'synthetic-food-vs-traditional', topic: 'synthetic food vs traditional food', category: 'lifestyle', style: 'lifestyle' },
      { id: 'no-alcohol-lifestyle-pressure', topic: 'no alcohol lifestyle pressure', category: 'lifestyle', style: 'lifestyle' },
      { id: 'four-day-week-less-pay', topic: 'working four days for less pay', category: 'lifestyle', style: 'lifestyle' },
      { id: 'deleting-dating-apps', topic: 'deleting dating apps', category: 'lifestyle', style: 'lifestyle' },
      { id: 'living-with-parents-save-money', topic: 'living with parents to save money', category: 'lifestyle', style: 'lifestyle' },
      { id: 'choosing-no-children', topic: 'choosing no children', category: 'lifestyle', style: 'lifestyle' },
      { id: 'moving-quality-of-life', topic: 'moving for quality of life', category: 'lifestyle', style: 'lifestyle' },
      { id: 'luxury-convenience-environment', topic: 'luxury convenience vs environmental cost', category: 'lifestyle', style: 'lifestyle' },
      { id: 'experiences-vs-savings', topic: 'spending on experiences vs savings', category: 'lifestyle', style: 'lifestyle' },
      { id: 'public-gym-filming', topic: 'public gym filming', category: 'lifestyle', style: 'lifestyle' },
      { id: 'household-chores-time-income', topic: 'sharing household chores by time or income', category: 'lifestyle', style: 'lifestyle' },
    ],
  },
  {
    id: 'consumer-brand-safe',
    label: 'Consumer / Brand / Sponsored-safe',
    targetShare: 0.05,
    description: 'Consumer choices that can later support sponsored-safe concepts without feeling like ads.',
    seeds: [
      { id: 'trying-lab-grown-food', topic: 'trying lab-grown food', category: 'lifestyle', style: 'lifestyle' },
      { id: 'ethical-products-pay-more', topic: 'paying more for ethical products', category: 'society', style: 'moral' },
      { id: 'brand-boycott-scandal', topic: 'boycotting a brand after scandal', category: 'society', style: 'moral' },
      { id: 'subscription-fatigue', topic: 'subscription fatigue', category: 'lifestyle', style: 'lifestyle' },
      { id: 'buying-refurbished-tech', topic: 'buying refurbished tech', category: 'technology', style: 'moral' },
      { id: 'returning-worn-clothing', topic: 'returning worn clothing', category: 'morality', style: 'moral' },
      { id: 'buy-now-pay-later', topic: 'using buy-now-pay-later', category: 'lifestyle', style: 'lifestyle' },
      { id: 'paying-for-ad-free-apps', topic: 'paying for ad-free apps', category: 'lifestyle', style: 'lifestyle' },
      { id: 'privacy-over-convenience', topic: 'choosing privacy over convenience', category: 'technology', style: 'moral' },
      { id: 'fast-delivery-worker-conditions', topic: 'fast delivery vs worker conditions', category: 'justice', style: 'moral' },
      { id: 'dynamic-pricing-fairness', topic: 'dynamic pricing fairness', category: 'justice', style: 'moral' },
      { id: 'loyalty-program-tracking', topic: 'loyalty programs tracking behavior', category: 'technology', style: 'moral' },
      { id: 'renting-instead-owning', topic: 'renting instead of owning', category: 'lifestyle', style: 'lifestyle' },
      { id: 'fake-scarcity-marketing', topic: 'fake scarcity marketing', category: 'morality', style: 'moral' },
      { id: 'influencer-product-disclosure', topic: 'influencer product disclosure', category: 'society', style: 'moral' },
    ],
  },
  {
    id: 'current-events-evergreen',
    label: 'Current-events-inspired Evergreen',
    targetShare: 0.07,
    description: 'Timely-feeling angles without naming real people, accusing named entities, or depending on specific facts.',
    seeds: [
      { id: 'artist-artwork-scandal', topic: 'separating artist from artwork after scandal', category: 'society', style: 'moral' },
      { id: 'public-figures-private-speech', topic: 'public figures losing jobs for private speech', category: 'freedom', style: 'moral' },
      { id: 'tech-founders-public-platforms', topic: 'tech founders controlling public platforms', category: 'technology', style: 'moral' },
      { id: 'athletes-national-event-protest', topic: 'athletes protesting during national events', category: 'society', style: 'moral' },
      { id: 'companies-political-positions', topic: 'companies taking political positions', category: 'society', style: 'moral' },
      { id: 'foreign-owned-app-ban', topic: 'governments banning foreign-owned apps', category: 'technology', style: 'moral' },
      { id: 'billionaires-public-projects', topic: 'billionaires funding public projects', category: 'society', style: 'moral' },
      { id: 'social-media-viral-trials', topic: 'viral trials by social media', category: 'justice', style: 'moral' },
      { id: 'misinformation-emergencies', topic: 'misinformation during emergencies', category: 'society', style: 'moral' },
      { id: 'classified-leaks-whistleblowers', topic: 'whistleblowers leaking classified documents', category: 'loyalty', style: 'moral' },
      { id: 'private-jets-celebrities', topic: 'celebrities using private jets', category: 'society', style: 'moral' },
      { id: 'strikes-disrupt-public-services', topic: 'strikes disrupting public services', category: 'society', style: 'moral' },
      { id: 'ai-public-data-training', topic: 'AI companies using public data', category: 'technology', style: 'moral' },
      { id: 'schools-culture-war-debates', topic: 'schools reacting to culture-war debates', category: 'society', style: 'moral' },
      { id: 'public-apologies-backlash', topic: 'public apologies after backlash', category: 'society', style: 'moral' },
    ],
  },
  {
    id: 'fun-low-stakes-viral',
    label: 'Fun / Low-stakes Viral',
    targetShare: 0.05,
    description: 'Low-stakes viral hooks that are still choices with trade-offs, not empty preference polls.',
    seeds: [
      { id: 'truth-or-believed', topic: 'always know the truth or always be believed', category: 'lifestyle', style: 'lifestyle' },
      { id: 'no-phone-or-no-travel', topic: 'one year without phone or one year without travel', category: 'lifestyle', style: 'lifestyle' },
      { id: 'free-rent-or-dream-job', topic: 'free rent forever or dream job guaranteed', category: 'lifestyle', style: 'lifestyle' },
      { id: 'public-life-or-private-life', topic: 'live publicly with no secrets or privately with no fame', category: 'lifestyle', style: 'lifestyle' },
      { id: 'restart-life-or-continue-money', topic: 'restart your life with memories or continue with money', category: 'lifestyle', style: 'lifestyle' },
      { id: 'loved-by-everyone-or-known-by-few', topic: 'be loved by everyone or deeply known by few', category: 'relationships', style: 'moral' },
      { id: 'never-lie-or-never-lied-to', topic: 'never lie or never be lied to', category: 'morality', style: 'moral' },
      { id: 'read-minds-or-hide-thoughts', topic: 'read minds or hide all your thoughts', category: 'lifestyle', style: 'lifestyle' },
      { id: 'health-or-money', topic: 'perfect health or unlimited money', category: 'lifestyle', style: 'lifestyle' },
      { id: 'fame-one-year-or-comfort', topic: 'fame for one year or comfort forever', category: 'lifestyle', style: 'lifestyle' },
      { id: 'know-when-or-how-you-die', topic: 'know when you die or know how you die', category: 'morality', style: 'moral' },
      { id: 'undo-mistake-or-future-success', topic: 'undo one mistake or guarantee one future success', category: 'lifestyle', style: 'lifestyle' },
      { id: 'always-early-or-calm', topic: 'always be early or always be calm', category: 'lifestyle', style: 'lifestyle' },
      { id: 'lose-social-or-streaming', topic: 'lose social media or lose streaming', category: 'lifestyle', style: 'lifestyle' },
      { id: 'past-wealth-or-future-uncertainty', topic: 'live in the past with wealth or future with uncertainty', category: 'lifestyle', style: 'lifestyle' },
    ],
  },
]

export function getAllContentSeeds(): ContentSeed[] {
  return CONTENT_SEED_PACKS.flatMap((pack) =>
    pack.seeds.map((seed) => ({ ...seed, packId: pack.id })),
  )
}

export function getContentSeedsByPack(packId: string): ContentSeed[] {
  return getAllContentSeeds().filter((seed) => seed.packId === packId)
}

export function getContentSeedsByStyle(style: ContentSeedStyle): ContentSeed[] {
  return getAllContentSeeds().filter((seed) => seed.style === style)
}
